{% set name = "sc-3d" %}
{% set version = "1.0.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/sc-3D-{{ version }}.tar.gz
  sha256: 62549f7843964ae88604f0c1aa6798ef8c84a9f122e616c1e9276fce5b4c436b

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.8
  run:
    - anndata
    - matplotlib-base
    - numpy
    - pandas
    - python >=3.8
    - scikit-learn
    - scipy
    - seaborn

test:
  imports:
    - sc3D
  commands:
    - pip list
    - pip check
  requires:
    - pip

about:
  home: https://pypi.org/project/sc-3D/
  summary: Array alignment and 3D differential expression for 3D sc omics
  license: MIT
  license_file: LICENSE
  dev_url: https://github.com/GuignardLab/sc3D

extra:
  recipe-maintainers:
    - goanpeca
    - jaimergp
    - leoguignard
