{% set name = "sc-3d" %}
{% set version = "1.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/sc-3D-{{ version }}.tar.gz
  sha256: d83de0dde6ce34faa8606a27939a98363b2b440a505b75d0197f7f2ab5c39e0b

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - pip
    - python {{ python_min }}
  run:
    - anndata
    - matplotlib-base
    - numpy
    - pandas
    - python >={{ python_min }}
    - scikit-learn
    - scipy
    - seaborn

test:
  imports:
    - sc3D
  commands:
    - pip list
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://pypi.org/project/sc-3D/
  summary: Array alignment and 3D differential expression for 3D sc omics
  license: MIT
  license_file: LICENSE
  dev_url: https://github.com/GuignardLab/sc3D

extra:
  recipe-maintainers:
    - goanpeca
    - jaimergp
    - leoguignard
