{% set name = "sc-3d" %}
{% set version = "1.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/sc-3D-{{ version }}.tar.gz
  sha256: e4938f1b3f316fd6f23b54b0ae3667f0ab446c7528f0e5941086129d480ad059

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.8
  run:
    - anndata
    - matplotlib-base
    - numpy
    - pandas
    - python >=3.8
    - scikit-learn
    - scipy
    - seaborn
    - transformations

test:
  imports:
    - sc3D
  commands:
    - pip list
    - pip check
  requires:
    - pip

about:
  home: https://github.com/GuignardLab/sc3D
  summary: Array alignment and 3D differential expression for 3D sc omics
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - goanpeca
    - jaimergp
    - leoguignard
