{% set name = "sc-3d" %}
{% set version = "1.2.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: d6c16cf114b7684dba5a09a11c0c4dbad1bd5287a5f60844d377a6c723df72f0

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python {{ python_min }}
  run:
    - anndata
    - matplotlib-base
    - numpy
    - pandas
    - python >={{ python_min }}
    - scikit-learn
    - scipy
    - seaborn

test:
  imports:
    - sc3D
  commands:
    - pip list
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://pypi.org/project/sc-3D/
  summary: Array alignment and 3D differential expression for 3D sc omics
  license: MIT
  license_file: LICENSE
  dev_url: https://github.com/GuignardLab/sc3D

extra:
  recipe-maintainers:
    - goanpeca
    - jaimergp
    - leoguignard
